ng_sme = {
    "Abuja Designs": {
        "Advertising Spend": 2000,
        "Average Annual Expenses": 190000,
        "Average Annual Revenue": 200000,
        "Average Gross Margin": 5,
        "Average Marketing Budget": 5000,
        "Average Profit Margin": 3,
        "Average Profit/Loss": 10000,
        "Customer Acquisition Cost": 400,
        "Customer Retention Rate": 35,
        "Employee Turnover Rate": 28,
        "Net Worth": -5000,
        "Number of Employees": 25,
        "Payroll Expenses": 120000,
        "Sales Conversion Rate": 3,
        "Sales Growth Rate": 1,
        "Total Social Media Followers": 50,
        "Training and Development": 1,
        "Working Capital": -1000,
        "Years Active": 2,
    },
    "Adebayo Logistics": {
        "Advertising Spend": 5000,
        "Average Annual Expenses": 390000,
        "Average Annual Revenue": 400000,
        "Average Gross Margin": 10,
        "Average Marketing Budget": 15000,
        "Average Profit Margin": 5,
        "Average Profit/Loss": 10000,
        "Customer Acquisition Cost": 300,
        "Customer Retention Rate": 40,
        "Employee Turnover Rate": 30,
        "Net Worth": -15000,
        "Number of Employees": 45,
        "Payroll Expenses": 200000,
        "Sales Conversion Rate": 5,
        "Sales Growth Rate": 2,
        "Total Social Media Followers": 150,
        "Training and Development": 2,
        "Working Capital": -5000,
        "Years Active": 3,
    },
    "Chukwu & Sons": {
        "Advertising Spend": 50000,
        "Average Annual Expenses": 1500000,
        "Average Annual Revenue": 2000000,
        "Average Gross Margin": 40,
        "Average Marketing Budget": 100000,
        "Average Profit Margin": 20,
        "Average Profit/Loss": 500000,
        "Customer Acquisition Cost": 150,
        "Customer Retention Rate": 85,
        "Employee Turnover Rate": 8,
        "Net Worth": 500000,
        "Number of Employees": 150,
        "Payroll Expenses": 800000,
        "Sales Conversion Rate": 25,
        "Sales Growth Rate": 15,
        "Total Social Media Followers": 10000,
        "Training and Development": 12,
        "Working Capital": 200000,
        "Years Active": 10,
    },
    "EkoTech": {
        "Advertising Spend": 80000,
        "Average Annual Expenses": 1800000,
        "Average Annual Revenue": 2500000,
        "Average Gross Margin": 45,
        "Average Marketing Budget": 150000,
        "Average Profit Margin": 25,
        "Average Profit/Loss": 700000,
        "Customer Acquisition Cost": 100,
        "Customer Retention Rate": 92,
        "Employee Turnover Rate": 5,
        "Net Worth": 800000,
        "Number of Employees": 120,
        "Payroll Expenses": 1000000,
        "Sales Conversion Rate": 30,
        "Sales Growth Rate": 20,
        "Total Social Media Followers": 15000,
        "Training and Development": 15,
        "Working Capital": 300000,
        "Years Active": 12,
    },
    "Lagos AgriHub": {
        "Advertising Spend": 50000,
        "Average Annual Expenses": 1500000,
        "Average Annual Revenue": 2000000,
        "Average Gross Margin": 40,
        "Average Marketing Budget": 100000,
        "Average Profit Margin": 20,
        "Average Profit/Loss": 500000,
        "Customer Acquisition Cost": 150,
        "Customer Retention Rate": 85,
        "Employee Turnover Rate": 8,
        "Net Worth": 500000,
        "Number of Employees": 150,
        "Payroll Expenses": 800000,
        "Sales Conversion Rate": 25,
        "Sales Growth Rate": 15,
        "Total Social Media Followers": 10000,
        "Training and Development": 12,
        "Working Capital": 200000,
        "Years Active": 10,
    },
    "NaijaMart": {
        "Advertising Spend": 20000,
        "Average Annual Expenses": 600000,
        "Average Annual Revenue": 800000,
        "Average Gross Margin": 30,
        "Average Marketing Budget": 50000,
        "Average Profit Margin": 22,
        "Average Profit/Loss": 200000,
        "Customer Acquisition Cost": 100,
        "Customer Retention Rate": 88,
        "Employee Turnover Rate": 6,
        "Net Worth": 200000,
        "Number of Employees": 50,
        "Payroll Expenses": 250000,
        "Sales Conversion Rate": 18,
        "Sales Growth Rate": 10,
        "Total Social Media Followers": 3000,
        "Training and Development": 8,
        "Working Capital": 50000,
        "Years Active": 8,
    },
    "Oga Foods": {
        "Advertising Spend": 3000,
        "Average Annual Expenses": 480000,
        "Average Annual Revenue": 500000,
        "Average Gross Margin": 8,
        "Average Marketing Budget": 10000,
        "Average Profit Margin": 4,
        "Average Profit/Loss": 20000,
        "Customer Acquisition Cost": 350,
        "Customer Retention Rate": 30,
        "Employee Turnover Rate": 25,
        "Net Worth": -10000,
        "Number of Employees": 35,
        "Payroll Expenses": 180000,
        "Sales Conversion Rate": 4,
        "Sales Growth Rate": 1,
        "Total Social Media Followers": 100,
        "Training and Development": 1,
        "Working Capital": -2000,
        "Years Active": 2,
    },
    "Omalicha Wears": {
        "Advertising Spend": 10000,
        "Average Annual Expenses": 580000,
        "Average Annual Revenue": 600000,
        "Average Gross Margin": 9,
        "Average Marketing Budget": 15000,
        "Average Profit Margin": 8,
        "Average Profit/Loss": 20000,
        "Customer Acquisition Cost": 300,
        "Customer Retention Rate": 50,
        "Employee Turnover Rate": 18,
        "Net Worth": -20000,
        "Number of Employees": 60,
        "Payroll Expenses": 250000,
        "Sales Conversion Rate": 8,
        "Sales Growth Rate": 4,
        "Total Social Media Followers": 400,
        "Training and Development": 2,
        "Working Capital": -5000,
        "Years Active": 3,
    },
    "Yemi Electronics": {
        "Advertising Spend": 1000,
        "Average Annual Expenses": 280000,
        "Average Annual Revenue": 300000,
        "Average Gross Margin": 6,
        "Average Marketing Budget": 5000,
        "Average Profit Margin": 7,
        "Average Profit/Loss": 20000,
        "Customer Acquisition Cost": 200,
        "Customer Retention Rate": 40,
        "Employee Turnover Rate": 15,
        "Net Worth": -1000,
        "Number of Employees": 15,
        "Payroll Expenses": 80000,
        "Sales Conversion Rate": 5,
        "Sales Growth Rate": 2,
        "Total Social Media Followers": 50,
        "Training and Development": 1,
        "Working Capital": -500,
        "Years Active": 1,
    },
    "Zobo Ventures": {
        "Advertising Spend": 8000,
        "Average Annual Expenses": 680000,
        "Average Annual Revenue": 700000,
        "Average Gross Margin": 12,
        "Average Marketing Budget": 30000,
        "Average Profit Margin": 6,
        "Average Profit/Loss": 20000,
        "Customer Acquisition Cost": 400,
        "Customer Retention Rate": 45,
        "Employee Turnover Rate": 22,
        "Net Worth": -30000,
        "Number of Employees": 100,
        "Payroll Expenses": 300000,
        "Sales Conversion Rate": 6,
        "Sales Growth Rate": 3,
        "Total Social Media Followers": 300,
        "Training and Development": 4,
        "Working Capital": -10000,
        "Years Active": 5,
    },
}
